### PR TITLE
Milestone 3 TicTacToe Project

### PR DESCRIPTION
**Pull request by denisdiaconu**
In this project, we build a Tic Tac Toe game using ruby. 
In this Project, two users can select their names and symbols and the winner is the one that gets 3 horizontal, vertical, or diagonal sequences.

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED!! :recycle: :red_circle: 
--------------
Hello team!! :wave: Your project looks really nice!! :muscle: I really like that you can choose your own mark. 
However, you have to work on some changes :hammer_and_wrench: . see them below :point_down: 
------------------

- [x] You have `puts` and `gets.chomp` outside the main file, remember that you shouldn't use puts/print and gets.chomp outside main.rb file
only_main_print

- [x] The game allows moving into an occupied position. Remember that the game should inform if the move's already taken and does not allow a player to move into an occupied position. 
- [x] The game does not inform the player if it is an invalid move, the game should inform about the invalid move and asks the player for their move again.
- [x] The game is no telling if the game is a draw, the application should tell if there was a draw after players move.
-----------------------
Make the required changes :point_up: and send it for another review. 
HAPPY CODDING!! 

AngelicConcreteHypsilophodon-max-1mb

**Comment by denisdiaconu** [comment]
Thank you for the code rev!
We fixed all the requirements, kindly review it again.

**Review by kevcap — CHANGES_REQUESTED** [review]
### Hey, nice project so far. We only have to improve a few things before moving on:

Nice job so far, I really liked the effort you put into this project! We just have to do some minor changes so we can approve this project:

- [x] You still has puts outisde the `main.rb` file. Please fix it.
## As always, I wish you all the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

[](https://microverse-students.slack.com/team/UT86D3AP4)

**Comment by nganifaith** [comment]
Thank you for your timely feedback, We've worked on the changes requested.

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: :smile: 
------------
Hello, again team!! :wave: excellent job working on the required changes :clap: :+1: 
------------

- [x] Improve your commits. On the coming projects write properly commit messages. Remember that you should write your commits in the imperative [Here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can find a refresh on how to write excellent commit messages.
--------------
Now you can merge this branch :clap: 
GREAT WORK!! HAPPY CODING AND GOOD LUCK ON THE NEXT ONES :four_leaf_clover: :crossed_fingers:

**Pull request merged**
